### ISSUE TITLE
Question: multiple interactive/editable views into the same content

### ISSUE THREAD

**Issue by oakad** [andy-goryachev/FxEditor#4]
Hi.

I wonder, have you looked into a problem of having multiple views (panes or windows) looking into the same editable content, in such a way, that edits happening in one pane are reflected in the all other views (such a feature is present in all decent editors, after all).

Recently, I had to look into a similar problem yet I could not identify an efficient way to update multiple scene graphs with the same content.

Do you plan to support such a feature in your FxEditor component (I checked the feature spreadsheet, but could not see if it's there)?

**Comment by andy-goryachev** [comment]
In theory, this should be a function of the model.  Editing does not work yet: still need to implement at least the basic plain text editable model.  Once this is done, it will be relatively easy to add multi-view capability to the model.

Thank you for your suggestion though.  I'll add this to the feature list.

Just curious, are you using it in a product?

**Comment by oakad** [comment]
Not yet. I'm still going through technology evaluation phase.

I'd love to go with pure Java(fx) solution, but many things "just work" in Qt (minus whatever amount of JNI mess).

**Comment by andy-goryachev** [comment]
I see.  This project is nowhere near production quality.  I might suggest to look at https://github.com/FXMisc/RichTextFX or indeed any other possible alternative since I, regretfully, have very little time to spend on this project at the present time.
